'use client';

import { useState, type CSSProperties } from 'react';
import { BarChart3, Briefcase, CalendarClock, ChevronLeft, ChevronRight, Clock3, Crown, Download, Eye, Globe, Camera, LayoutGrid, List, Mail, MapPin, MessageSquare, Phone, Plus, Search, SlidersHorizontal, Target, Trophy, UserPlus, Users, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import './leads.css';

type SeedLead = { name: string; company: string; stage: string; source: string; age: string; temperature: string };
type Lead = SeedLead & { id: number; platform: string; phone: string; email: string; city: string; budget: string; service: string; timeline: string; owner: string; followUp: string; notes: string };
const stageNames = ['New', 'Contacted', 'Interested', 'Proposal Sent', 'Ringing', 'Won', 'Lost'];
const stageColors: Record<string, string> = { New: '#818cf8', Contacted: '#d99b1c', Interested: '#f07836', 'Proposal Sent': '#9865df', Ringing: '#c48c1c', Won: '#21a978', Lost: '#6486ac' };
const platforms = ['Facebook', 'Instagram', 'Website'];
const emptyLead: Lead = { id: 0, name: '', company: '', stage: 'New', source: 'Website', platform: 'Website', age: 'Just now', temperature: '', phone: '', email: '', city: '', budget: '', service: '', timeline: '', owner: '', followUp: 'No follow-up', notes: '' };
function tone(stage: string) { return stage === 'Proposal Sent' ? 'proposal' : stage.toLowerCase(); }
function exportLeads(leads: Lead[]) {
  const keys = ['name', 'company', 'phone', 'email', 'city', 'platform', 'stage', 'budget', 'owner', 'followUp'] as const;
  const escape = (value: string) => `"${(/^[=+@-]/.test(value) ? "'" : '') + value.replaceAll('"', '""')}"`;
  const csv = [keys.join(','), ...leads.map(lead => keys.map(key => escape(lead[key])).join(','))].join('\r\n');
  const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8;' }));
  const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'crm-leads.csv'; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export default function LeadsExplorer({ initialLeads }: { initialLeads: SeedLead[] }) {
  const [leads, setLeads] = useState<Lead[]>(() => initialLeads.map((lead, i) => ({ ...lead, id: initialLeads.length - i, stage: lead.stage === 'New Leads' ? 'New' : lead.stage === 'Closed' ? 'Won' : i === 5 || i === 7 ? 'Ringing' : lead.stage, platform: lead.source === 'Instagram' ? 'Instagram' : lead.source === 'Meta Ads' ? 'Facebook' : 'Website', phone: '', email: '', city: ['Mumbai', 'Delhi', 'Bengaluru', 'Pune', 'Noida'][i % 5], budget: ['₹50,000 – ₹1L', '₹1L – ₹2L', '₹25,000 – ₹50,000'][i % 3], service: ['Social Media', 'Brand Campaign', 'Website Design'][i % 3], timeline: ['This month', 'Within 3 months', 'Immediately'][i % 3], owner: i % 4 === 0 ? '' : ['Aman Gupta', 'Ritika Das', 'Karan Verma'][i % 3], followUp: ['No follow-up', 'Due Today', 'Upcoming (7d)', 'Overdue'][i % 4], notes: '' })));
  const [query, setQuery] = useState('');
  const [platform, setPlatform] = useState('All Platforms');
  const [stage, setStage] = useState('All Stages');
  const [followUp, setFollowUp] = useState('Follow-ups');
  const [owner, setOwner] = useState('All Owners');
  const [city, setCity] = useState('All Cities');
  const [priority, setPriority] = useState('All Priorities');
  const [filters, setFilters] = useState(false);
  const [analytics, setAnalytics] = useState(false);
  const [view, setView] = useState('Cards');
  const [newest, setNewest] = useState(true);
  const [page, setPage] = useState(1);
  const [selected, setSelected] = useState<number[]>([]);
  const [draft, setDraft] = useState<Lead | null>(null);
  const [detailTab, setDetailTab] = useState('Overview');
  const [notice, setNotice] = useState('');
  const [bulkStage, setBulkStage] = useState('New');
  const [scope, setScope] = useState('All Leads');
  const filtered = leads.filter(lead => Object.values(lead).join(' ').toLowerCase().includes(query.toLowerCase()) && (platform === 'All Platforms' || lead.platform === platform) && (stage === 'All Stages' || lead.stage === stage) && (followUp === 'Follow-ups' || lead.followUp === followUp) && (owner === 'All Owners' || (owner === 'Unassigned' ? !lead.owner : lead.owner === owner)) && (city === 'All Cities' || lead.city === city) && (priority === 'All Priorities' || lead.temperature === priority) && (scope === 'All Leads' || lead.owner === 'Aman Gupta')).sort((a, b) => newest ? b.id - a.id : a.id - b.id);
  const totalPages = Math.max(1, Math.ceil(filtered.length / 12));
  const currentPage = Math.min(page, totalPages);
  const visible = filtered.slice((currentPage - 1) * 12, currentPage * 12);
  const reset = () => { setQuery(''); setPlatform('All Platforms'); setStage('All Stages'); setFollowUp('Follow-ups'); setOwner('All Owners'); setCity('All Cities'); setPriority('All Priorities'); setScope('All Leads'); setPage(1); };
  const toggleSelected = (id: number) => setSelected(selected.includes(id) ? selected.filter(value => value !== id) : [...selected, id]);
  const openLead = (lead: Lead, tab = 'Overview') => { setDraft({ ...lead }); setDetailTab(tab); };
  const count = (predicate: (lead: Lead) => boolean) => leads.filter(predicate).length;
  const filterCount = [platform !== 'All Platforms', stage !== 'All Stages', followUp !== 'Follow-ups', owner !== 'All Owners', city !== 'All Cities', priority !== 'All Priorities'].filter(Boolean).length;
  const applyStage = () => { setLeads(leads.map(lead => selected.includes(lead.id) ? { ...lead, stage: bulkStage } : lead)); setNotice(`${selected.length} leads moved to ${bulkStage}.`); setSelected([]); };
  const platformMark = (value: string) => value === 'Instagram' ? <Camera size={11}/> : value === 'Website' ? <Globe size={11}/> : <span aria-hidden="true">f</span>;
  const stageBadge = (lead: Lead) => <span className="lx-stage" style={{ background: stageColors[lead.stage] }}>{lead.stage}</span>;
  const select = (label: string, value: string, options: string[], change: (value: string) => void) => <select aria-label={label} value={value} onChange={e => { change(e.target.value); setPage(1); }}>{options.map(option => <option key={option}>{option}</option>)}</select>;
  return <section className="lx-leads">
    <div className="lx-heading"><div><h3>Leads</h3><p>Every opportunity. One clear view.</p></div><div className="lx-heading-actions"><Button className="ws-button" onClick={() => { setDraft({ ...emptyLead }); setDetailTab('Overview'); }}><UserPlus size={14}/>Add Lead</Button><button className="lx-icon-button" aria-label="Export leads as CSV" title="Export CSV" onClick={() => exportLeads(selected.length ? leads.filter(lead => selected.includes(lead.id)) : filtered)}><Download size={15}/></button><button className={`lx-icon-button ${analytics ? 'active' : ''}`} aria-label="Toggle lead analytics" aria-pressed={analytics} title="Analytics" onClick={() => setAnalytics(!analytics)}><BarChart3 size={15}/></button></div></div>
    <div className="lx-summary" aria-label="Lead summary filters">
      <button className="indigo" onClick={reset}><Users size={12}/>{leads.length} leads</button>
      <button className="amber" onClick={() => { setFollowUp('Due Today'); setPage(1); }}><Clock3 size={12}/>{count(lead => lead.followUp === 'Due Today')} due today</button>
      <button className="red" onClick={() => { setFollowUp('Overdue'); setPage(1); }}><CalendarClock size={12}/>{count(lead => lead.followUp === 'Overdue')} overdue</button>
      <button className="violet" onClick={() => { setFollowUp('Upcoming (7d)'); setPage(1); }}>{count(lead => lead.followUp === 'Upcoming (7d)')} upcoming</button>
      <button className="orange" onClick={() => { setOwner('Unassigned'); setPage(1); }}>{count(lead => !lead.owner)} unassigned</button>
      <button className="green" onClick={() => { setStage('Won'); setPage(1); }}><Trophy size={12}/>{count(lead => lead.stage === 'Won')} won</button>
      <button className="cyan" onClick={() => setAnalytics(!analytics)}>{Math.round(count(lead => lead.stage === 'Won') / Math.max(1, leads.length) * 100)}% conv</button>
      {platforms.map(item => <button key={item} className={item === 'Facebook' ? 'indigo' : item === 'Instagram' ? 'violet' : 'green'} aria-label={`Filter ${item} leads`} onClick={() => { setPlatform(platform === item ? 'All Platforms' : item); setPage(1); }}>{platformMark(item)}{count(lead => lead.platform === item)}</button>)}
      <button className="lx-ringing" onClick={() => { const candidates = leads.filter(lead => lead.stage === 'Ringing'); if (candidates.length) { openLead(candidates[Math.floor(Math.random() * candidates.length)]); setNotice('Ringing of the Day: a lead to follow up with next.'); } else setNotice('No ringing leads at the moment.'); }}><Crown size={12}/>Ringing of the Day</button>
    </div>
    {analytics && <div className="lx-analytics"><article><h4><Target size={14}/>Stage Pipeline</h4>{stageNames.map(item => <button key={item} onClick={() => { setStage(item); setPage(1); }}><span>{item}</span><div><i style={{ width: `${count(lead => lead.stage === item) / Math.max(1, leads.length) * 100}%`, background: stageColors[item] }}/></div><b>{count(lead => lead.stage === item)}</b></button>)}</article><article><h4><BarChart3 size={14}/>Lead Sources</h4>{platforms.map(item => <button key={item} onClick={() => { setPlatform(item); setPage(1); }}><span>{item}</span><div><i style={{ width: `${count(lead => lead.platform === item) / Math.max(1, leads.length) * 100}%`, background: item === 'Instagram' ? '#b46de5' : item === 'Website' ? '#38bfa1' : '#6c7df2' }}/></div><b>{count(lead => lead.platform === item)}</b></button>)}<p>{count(lead => lead.stage === 'Won')} opportunities won out of {leads.length} leads.</p></article></div>}
    <div className="lx-filter-panel"><div className="lx-filter-row"><label className="lx-search" htmlFor="leads-search"><Search size={15}/><Input id="leads-search" placeholder="Search leads..." value={query} onChange={e => { setQuery(e.target.value); setPage(1); }}/></label>{select('Platform', platform, ['All Platforms', ...platforms], setPlatform)}{select('Stage', stage, ['All Stages', ...stageNames], setStage)}{select('Follow-up', followUp, ['Follow-ups', 'Due Today', 'Overdue', 'Upcoming (7d)', 'No follow-up'], setFollowUp)}<button className={`lx-filter-button ${filters ? 'active' : ''}`} onClick={() => setFilters(!filters)} aria-expanded={filters}><SlidersHorizontal size={14}/>Filters{filterCount > 0 && <b>{filterCount}</b>}</button><button className="lx-filter-button" onClick={() => { setNewest(!newest); setPage(1); }}>{newest ? '↓ Newest' : '↑ Oldest'}</button><div className="lx-view-switch"><button aria-label="Card view" aria-pressed={view === 'Cards'} className={view === 'Cards' ? 'active' : ''} onClick={() => setView('Cards')}><LayoutGrid size={15}/></button><button aria-label="Table view" aria-pressed={view === 'Table'} className={view === 'Table' ? 'active' : ''} onClick={() => setView('Table')}><List size={15}/></button></div></div>
    {filters && <div className="lx-extra-filters"><div><span>Owner</span>{select('Owner', owner, ['All Owners', 'Unassigned', 'Aman Gupta', 'Ritika Das', 'Karan Verma'], setOwner)}</div><div><span>City</span>{select('City', city, ['All Cities', ...Array.from(new Set(leads.map(lead => lead.city).filter(Boolean)))], setCity)}</div><div><span>Priority</span>{select('Priority', priority, ['All Priorities', 'Hot', 'Warm', 'Won', 'Lost'], setPriority)}</div><button className="ws-link" onClick={reset}>Clear all filters</button></div>}</div>
    <div className="lx-results-bar"><div className="lx-scope">{['All Leads', 'My Leads'].map(item => <button key={item} className={scope === item ? 'active' : ''} aria-pressed={scope === item} onClick={() => { setScope(item); setPage(1); }}>{item}</button>)}</div><span>{filtered.length} results{(filterCount > 0 || query) && <button onClick={reset}>Clear filters<X size={11}/></button>}</span></div>
    {notice && <output className="lx-notice">{notice}<button aria-label="Dismiss notification" onClick={() => setNotice('')}><X size={14}/></button></output>}
    {selected.length > 0 && <div className="lx-bulk"><strong>{selected.length} selected</strong>{select('Bulk stage', bulkStage, stageNames, setBulkStage)}<button onClick={applyStage}>Update stage</button><button onClick={() => exportLeads(leads.filter(lead => selected.includes(lead.id)))}>Export selected</button><button onClick={() => setSelected([])}>Clear selection</button></div>}
    {view === 'Cards' ? <div className="lx-grid">{visible.map(lead => <article key={lead.id} className={`lx-card lx-${tone(lead.stage)} ${selected.includes(lead.id) ? 'is-selected' : ''}`} style={{ '--lead-accent': stageColors[lead.stage] } as CSSProperties}>
      <div className="lx-card-strip"/><div className="lx-card-body"><header><button className={`lx-avatar platform-${lead.platform.toLowerCase()}`} onClick={() => openLead(lead)} aria-label={`View ${lead.name}`}>{lead.name[0]}</button><div><button className="lx-name" onClick={() => openLead(lead)}>{lead.name}</button><div className="lx-card-badges">{stageBadge(lead)}<span className={`lx-platform platform-${lead.platform.toLowerCase()}`}>{platformMark(lead.platform)}{lead.platform === 'Instagram' ? 'IG' : lead.platform === 'Facebook' ? 'FB' : 'WB'}</span>{lead.temperature === 'Hot' && <span className="lx-hot">Hot</span>}</div></div><div className="lx-card-select"><input type="checkbox" checked={selected.includes(lead.id)} onChange={() => toggleSelected(lead.id)} aria-label={`Select ${lead.name}`}/>{lead.followUp === 'Overdue' && <span>OVERDUE</span>}</div></header>
      <div className="lx-contact-info"><span><Phone size={12}/>{lead.phone || 'Phone not added'}</span><span><Mail size={12}/>{lead.email || 'Email not added'}</span><span><MapPin size={12}/>{lead.city || 'City not added'}</span></div>
      <div className="lx-attributes"><span>{lead.budget || 'Budget pending'}</span><span><Briefcase size={10}/>{lead.service || lead.company}</span><span><CalendarClock size={10}/>{lead.timeline || 'Timeline pending'}</span></div><p className="lx-campaign">{lead.company} · {lead.source}</p>
      <footer><span><Clock3 size={10}/>{lead.age}</span><span className={!lead.owner ? 'unassigned' : ''}>{lead.owner || 'Unassigned'}</span>{lead.followUp !== 'No follow-up' && <span className={lead.followUp === 'Overdue' ? 'overdue' : ''}><CalendarClock size={10}/>{lead.followUp}</span>}</footer>
      <div className="lx-card-actions">{lead.phone ? <a href={`tel:${lead.phone.replace(/[^+\d]/g, '')}`}><Phone size={12}/>Call</a> : <button onClick={() => openLead(lead, 'Contact')}><Phone size={12}/>Call</button>}{lead.phone ? <a href={`https://wa.me/${lead.phone.replace(/\D/g, '')}`} target="_blank" rel="noreferrer"><MessageSquare size={12}/>WhatsApp</a> : <button onClick={() => openLead(lead, 'Contact')}><MessageSquare size={12}/>WhatsApp</button>}<button onClick={() => openLead(lead)}><Eye size={12}/>Details</button></div></div>
    </article>)}</div> : <div className="lx-table"><table><thead><tr><th><input aria-label="Select visible leads" type="checkbox" checked={visible.length > 0 && visible.every(lead => selected.includes(lead.id))} onChange={e => setSelected(e.target.checked ? Array.from(new Set([...selected, ...visible.map(lead => lead.id)])) : selected.filter(id => !visible.some(lead => lead.id === id)))}/></th>{['Date', 'Contact', 'City', 'Platform', 'Campaign', 'Budget', 'Service', 'Timeline', 'Stage', 'Owner', 'Follow-up', 'Actions'].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{visible.map(lead => <tr key={lead.id}><td><input type="checkbox" checked={selected.includes(lead.id)} onChange={() => toggleSelected(lead.id)} aria-label={`Select ${lead.name}`}/></td><td>{lead.age}</td><td><button className="lx-table-name" onClick={() => openLead(lead)}>{lead.name}</button><small>{lead.phone || 'No phone added'}</small></td><td>{lead.city || '—'}</td><td><span className={`lx-platform platform-${lead.platform.toLowerCase()}`}>{platformMark(lead.platform)}{lead.platform}</span></td><td>{lead.company}</td><td>{lead.budget || '—'}</td><td>{lead.service || '—'}</td><td>{lead.timeline || '—'}</td><td>{stageBadge(lead)}</td><td>{lead.owner || 'Unassigned'}</td><td>{lead.followUp}</td><td><button className="lx-icon-button" aria-label={`Details for ${lead.name}`} onClick={() => openLead(lead)}><Eye size={14}/></button></td></tr>)}</tbody></table></div>}
    {!filtered.length && <div className="lx-empty"><Target size={35}/><h4>No leads found</h4><p>Try adjusting your search or filters.</p><button onClick={reset}>Reset filters</button></div>}
    <div className="lx-pagination"><span>Page {currentPage} of {totalPages} · {filtered.length} leads</span><div><button disabled={currentPage === 1} onClick={() => setPage(currentPage - 1)}><ChevronLeft size={14}/>Previous</button><button disabled={currentPage === totalPages} onClick={() => setPage(currentPage + 1)}>Next<ChevronRight size={14}/></button></div></div>
    <Dialog open={draft !== null} onOpenChange={open => { if (!open) setDraft(null); }}><DialogContent className="ws-dialog lx-dialog"><DialogTitle>{draft?.id ? draft.name : 'Add Lead Manually'}</DialogTitle><DialogDescription>{draft?.id ? 'Contact information and lead management.' : 'Add a new opportunity to your lead workspace.'}</DialogDescription>{draft && <><div className="lx-dialog-tabs">{['Overview', 'Contact', 'Notes'].map(tab => <button key={tab} className={detailTab === tab ? 'active' : ''} onClick={() => setDetailTab(tab)}>{tab}</button>)}</div><form onSubmit={event => { event.preventDefault(); setLeads(draft.id ? leads.map(lead => lead.id === draft.id ? draft : lead) : [{ ...draft, id: Math.max(0, ...leads.map(lead => lead.id)) + 1 }, ...leads]); setNotice(draft.id ? `${draft.name} updated.` : `${draft.name} added to leads.`); setDraft(null); }}>
    {detailTab === 'Overview' && <div className="lx-detail-fields">{([['name', 'Full Name'], ['company', 'Company'], ['city', 'City'], ['budget', 'Budget'], ['service', 'Service'], ['timeline', 'Timeline']] as const).map(([key, label]) => <label key={key} htmlFor={`lead-${key}`}>{label}<Input id={`lead-${key}`} required={key === 'name'} value={draft[key]} onChange={e => setDraft({ ...draft, [key]: e.target.value })}/></label>)}<div><span>Stage</span>{select('Lead stage', draft.stage, stageNames, value => setDraft({ ...draft, stage: value }))}</div><div><span>Platform</span>{select('Lead platform', draft.platform, platforms, value => setDraft({ ...draft, platform: value, source: value }))}</div><div><span>Owner</span>{select('Lead owner', draft.owner || 'Unassigned', ['Unassigned', 'Aman Gupta', 'Ritika Das', 'Karan Verma'], value => setDraft({ ...draft, owner: value === 'Unassigned' ? '' : value }))}</div><div><span>Follow-up</span>{select('Lead follow-up', draft.followUp, ['No follow-up', 'Due Today', 'Overdue', 'Upcoming (7d)'], value => setDraft({ ...draft, followUp: value }))}</div></div>}
    {detailTab === 'Contact' && <><p>Add a contact number to enable Call and WhatsApp.</p><label htmlFor="lead-phone">Phone<Input id="lead-phone" type="tel" value={draft.phone} onChange={e => setDraft({ ...draft, phone: e.target.value })}/></label><label htmlFor="lead-email">Email<Input id="lead-email" type="email" value={draft.email} onChange={e => setDraft({ ...draft, email: e.target.value })}/></label></>}
    {detailTab === 'Notes' && <label htmlFor="lead-notes">Notes<textarea id="lead-notes" rows={5} value={draft.notes} onChange={e => setDraft({ ...draft, notes: e.target.value })}/></label>}
    <div className="ws-actions"><Button type="button" className="ws-button ws-secondary" onClick={() => setDraft(null)}>Cancel</Button><Button type="submit" className="ws-button" disabled={!draft.name.trim()}>{draft.id ? 'Update Lead' : <><Plus size={14}/>Add Lead</>}</Button></div></form></>}</DialogContent></Dialog>
  </section>;
}
